jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # ... (Set up JDK, Cache Gradle dependencies, Create gradle.properties steps - these seem fine)

      - name: Create local.properties for front/app module
        run: |
          mkdir -p ./front/app # Ensure directory exists
          echo "ODsay_APIKEY=${{ secrets.ODsay_APIKEY }}" > ./front/app/local.properties
          echo "Geolocation_APIKEY=${{ secrets.Geolocation_APIKEY }}" >> ./front/app/local.properties
          echo "SMARTTHINGS_API_TOKEN=${{ secrets.SMARTTHINGS_API_TOKEN }}" >> ./front/app/local.properties
          echo "Public_Bus_APIKEY=${{ secrets.Public_Bus_APIKEY }}" >> ./front/app/local.properties
          echo "Public_Subway_APIKEY=${{ secrets.Public_Subway_APIKEY }}" >> ./front/app/local.properties
          echo "KAKAO_NATIVE_API_KEY=${{ secrets.KAKAO_NATIVE_API_KEY }}" >> ./front/app/local.properties

      # --- START OF MODIFIED SECTION ---

      - name: Grant execute permission for gradlew
        # Remove working-directory here. It will run from the repository root.
        run: chmod +x ./gradlew

      - name: Stop any running Gradle daemons
        # Remove working-directory here. It will run from the repository root.
        run: ./gradlew --stop || true

      - name: Build with Gradle
        # Remove working-directory here. It will run from the repository root.
        # Specify the module path explicitly.
        run: ./gradlew :front:app:assembleDebug --stacktrace --info

      - name: Run unit tests
        # Remove working-directory here. It will run from the repository root.
        # Specify the module path explicitly.
        run: ./gradlew :front:app:testDebugUnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          # Path remains relative to the repository root.
          path: ./front/app/build/reports/tests/testDebugUnitTest 

      - name: Upload APK (Debug)
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: app-debug
          # Path remains relative to the repository root.
          path: ./front/app/build/outputs/apk/debug/*.apk

      # --- END OF MODIFIED SECTION ---
