name: Android CI

on:
  push:
    branches: [ "main", "watch" ]
  pull_request:
    branches: [ "main", "watch" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle.properties', '**/settings.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create gradle.properties in project root and front module
        run: |
          # 프로젝트 루트에 생성
          echo "android.useAndroidX=true" > gradle.properties # ">" 사용: 항상 새 파일 생성
          echo "android.enableJetifier=true" >> gradle.properties
          # Java 17 환경에 맞게 MaxPermSize 제거, Xmx 메모리 상향 조정
          echo "org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties

          # front 모듈 디렉토리 안에도 복사
          if [ -d "./front" ]; then
            cp gradle.properties ./front/gradle.properties || true # 복사 실패해도 워크플로우 중단 방지
          else
            echo "::warning::'front' directory not found. Skipping gradle.properties copy to front module."
          fi

      - name: Create local.properties
        run: |
          # 요청에 따라 API 키 이름은 변경하지 않았습니다.
          echo "ODsay_APIKEY=${{ secrets.ODsay_APIKEY }}" > ./front/local.properties
          echo "Geolocation_APIKEY=${{ secrets.Geolocation_APIKEY }}" >> ./front/local.properties
          echo "SMARTTHINGS_API_TOKEN=${{ secrets.SMARTTHINGS_API_TOKEN }}" >> ./front/local.properties
          echo "Public_Bus_APIKEY=${{ secrets.Public_Bus_APIKEY }}" >> ./front/local.properties
          echo "Public_Subway_APIKEY=${{ secrets.Public_Subway_APIKEY }}" >> ./front/local.properties
          echo "KAKAO_NATIVE_API_KEY=${{ secrets.KAKAO_NATIVE_API_KEY }}" >> ./front/local.properties

      - name: Grant execute permission for gradlew
        working-directory: ./front
        run: chmod +x ./gradlew

      - name: Stop any running Gradle daemons
        working-directory: ./front
        run: ./gradlew --stop || true # --stop 명령이 실패해도 워크플로우가 멈추지 않도록 || true 추가

      - name: Build with Gradle
        working-directory: ./front
        run: ./gradlew assembleDebug

      - name: Run unit tests
        working-directory: ./front
        run: ./gradlew testDebugUnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./front/app/build/reports/tests/testDebugUnitTest # 일반적인 테스트 결과 경로

      - name: Upload APK (Debug)
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: app-debug
          path: ./front/app/build/outputs/apk/debug/*.apk
