name: Android Watch CI

on:
  push:
    branches: [ "main", "watch" ]
  pull_request:
    branches: [ "main", "watch" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: # 추가
      working-directory: ./front # 추가

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 필요에 따라 설정
          submodules: true # 필요에 따라 설정

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # front 폴더 안에서 실행되므로 ./gradlew로 변경 가능

      - name: Build with Gradle
        run: ./gradlew build # front 폴더 안에서 실행

      - name: Run unit tests
        run: ./gradlew test # front 폴더 안에서 실행

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest # 필요에 따라 경로 수정
